name: DynWarp
main: mario182.dynwarp.Main
version: 0.31
author: mario182
website: http://mario182.no-ip.org
commands:
    dynwarp:
      description: '-'
      usage: '-'
    warp:
      description: '-'
      usage: '-'
      aliases: [warpto]
    warpgroup:
      description: '-'
      usage: '-'
      aliases: [groupwarps, warpgroups]
    createwarp:
      description: '-'
      usage: '-'
      aliases: [addwarp, createwarp]
    deletewarp:
      description: '-'
      usage: '-'
      aliases: [removewarp, delwarp]
    warplist:
      description: '-'
      usage: '-'
      aliases: [listwarps]
    grouplist:
      description: '-'
      usage: '-'
      aliases: [listgroups]
depend: [dynmap]